# Generated by Django 5.1 on 2024-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_rename_bankappaccount_statuse_account_statuse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
